version: '3.8'

services:
  magrathea:
    build: .
    ports:
      - "9000:8080"
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - admin.server.port=8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 5s
      timeout: 3s
      retries: 10

  structurizr-local:
    image: docker.io/structurizr/structurizr
    command: local
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "9090:9090"
    environment:
      - PORT=9090
      - STRUCTURIZR_AUTOREFRESHINTERVAL=2000
      - STRUCTURIZR_AUTOSAVEINTERVAL=5000
    volumes:
      - ./docs/c4:/usr/local/structurizr
