graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Container View: Magrathea ObjectStorage"]
    style diagram fill:#ffffff,stroke:#ffffff

    1["<div style='font-weight: bold'>User</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>End user interacting via HTTP</div>"]
    style 1 fill:#ffffff,stroke:#444444,color:#444444

    subgraph 2 ["Magrathea ObjectStorage"]
      style 2 fill:#ffffff,stroke:#444444,color:#444444

      3["<div style='font-weight: bold'>Web Application</div><div style='font-size: 70%; margin-top: 0px'>[Container: S3 API endpoints, business logic, file persistence]</div><div style='font-size: 80%; margin-top:10px'>Spring Boot 4 WebFlux</div>"]
      style 3 fill:#ffffff,stroke:#444444,color:#444444
    end

  end