@startuml
title <size:24>Container View: Magrathea ObjectStorage</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

Person(User, "User", $descr="End user interacting via HTTP", $tags="", $link="")

System_Boundary("MagratheaObjectStorage_boundary", "Magrathea ObjectStorage", $tags="") {
  Container(MagratheaObjectStorage.WebApplication, "Web Application", $techn="S3 API endpoints, business logic, file persistence", $descr="Spring Boot 4 WebFlux", $tags="", $link="")
}

SHOW_LEGEND(true)
hide stereotypes
@enduml